"""edit columns types

Revision ID: 4c6f4918bba5
Revises: 74b69b715014
Create Date: 2024-08-24 20:01:29.379456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4c6f4918bba5"
down_revision: Union[str, None] = "74b69b715014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "quantity",
        existing_type=mysql.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "wallet_balance_after",
        existing_type=mysql.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "wallets",
        "balance",
        existing_type=mysql.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wallets",
        "balance",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "wallet_balance_after",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "quantity",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
