"""user-category relation

Revision ID: d50e6db88562
Revises: 3ad5a29cb9d0
Create Date: 2024-08-19 18:08:49.665896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d50e6db88562"
down_revision: Union[str, None] = "3ad5a29cb9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "categories", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "user_id")
    # ### end Alembic commands ###
