"""create wallets table

Revision ID: d026ff6449b4
Revises: bf08c04d3f39
Create Date: 2024-08-12 18:22:02.625863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d026ff6449b4"
down_revision: Union[str, None] = "bf08c04d3f39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=50), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallets")
    # ### end Alembic commands ###
