"""add column

Revision ID: 595dd09200aa
Revises: 696a9362d9e8
Create Date: 2024-08-18 14:03:36.620357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "595dd09200aa"
down_revision: Union[str, None] = "696a9362d9e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "accesstoken", "user", ["user_id"], ["id"], ondelete="cascade"
    )
    op.drop_column("accesstoken", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.drop_column("accesstoken", "user_id")
    # ### end Alembic commands ###
