"""add column to transactions

Revision ID: 74b69b715014
Revises: d50e6db88562
Create Date: 2024-08-24 19:54:18.270669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74b69b715014"
down_revision: Union[str, None] = "d50e6db88562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("wallet_balance_after", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "wallet_balance_after")
    # ### end Alembic commands ###
